Added a bit more logic to the mysql backup script to detect errors and exclude the information_schema database

diff --git a/mysql/templates/backup.sh.erb b/mysql/templates/backup.sh.erb
--- a/mysql/templates/backup.sh.erb
+++ b/mysql/templates/backup.sh.erb
@@ -12,17 +12,26 @@ backupError=0
 
 echo "Starting backup of all databases"
 
-# Run mysqldump on each database and output to an sql file
-/usr/bin/mysql -u<%= @backup_user %> -p<%= @backup_password %> -e 'show databases' | while read dbname; do
-  echo "Backing up $dbname"...
-  /usr/bin/mysqldump -u<%= @backup_user %> -p<%= @backup_password %> "$dbname" > "<%= @backup_path %>/$dbname".sql
-  if [ $? -ne 0 ]; then
-    backupError=1
+# Get a list of databases from the MySQL server
+databases=`/usr/bin/mysql -B -N -u<%= @backup_user %> -p<%= @backup_password %> -e 'show databases'`
+if [ $? -ne 0 ]; then
+  echo "There was an error connecting to the MySQL server." 1>&2
+  exit 100
+fi
+
+# Run mysqldump on each database and output to a .sql file
+for dbname in $databases; do
+  if [ "$dbname" != "information_schema" ]; then
+    echo "Backing up $dbname"...
+    /usr/bin/mysqldump -u<%= @backup_user %> -p<%= @backup_password %> "$dbname" > "<%= @backup_path %>/$dbname".sql
+    if [ $? -ne 0 ]; then
+      backupError=1
+    fi
   fi
 done
 
 # Make sure we had no errors. Return an error code if we did.
-if [ $backupError -ne 0 ] || [ $? -ne 0 ]; then
+if [ $backupError -ne 0 ]; then
   echo "There was an error backing up one or more databases." 1>&2
   exit 100
 fi
@@ -32,4 +41,5 @@ fi
 /usr/bin/find "<%= @backup_path %>"/*.sql -mtime +<%= @purge_days %> -exec rm {} \;
 <% end -%>
 
+echo "Database backup complete."
 exit 0
