Added a firewall rule and adjusted init script for logstash forwarder

diff --git a/logstashforwarder/templates/etc/init.d/logstashforwarder.RedHat.erb b/logstashforwarder/templates/etc/init.d/logstashforwarder.RedHat.erb
--- a/logstashforwarder/templates/etc/init.d/logstashforwarder.RedHat.erb
+++ b/logstashforwarder/templates/etc/init.d/logstashforwarder.RedHat.erb
@@ -1,74 +1,109 @@
-#!/bin/bash
-# chkconfig: 345 80 20
-# description: Logstash Forwarder
-# processname: logstash-forwarder
-# config: /etc/logstash-forwarder
-# pidfile: /var/run/logstash-forwarder.pid
-
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
+#!/bin/sh
+#
+#   /etc/init.d/logstash-forwarder
+#
+#   Starts and stops logstash-forwarder as a daemon.
+#
+# chkconfig: 2345 30 70
+# description: Starts and stops logstash-forwarder as a daemon.
+ 
+# The name of this service
 NAME=logstash-forwarder
-DAEMON=/opt/logstash-forwarder/bin/logstash-forwarder
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
+ 
+### Start Configuration Options ###
+ 
+# The JSON config to use
+LJ_CONFIG=/etc/logstashforwarder/config.json
+ 
+# The Lumberjack binary wrapper
+LJ_BIN=/opt/logstash-forwarder/bin/logstash-forwarder
 
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+# The Lumberjack runnning directory
+LJ_RUNDIR="$(dirname ${LJ_BIN})/.."
+ 
+# Any Lumberjack options
+LJ_OPTS="-spool-size 1000"
+ 
+# The log file for local info
+LJ_LOG=/var/log/logstash-forwarder/logstash-forwarder
+ 
+# The PID file
+PID_FILE=/var/run/logstash-forwarder
+ 
+# The command to daemonize
+DAEMON="nohup ${LJ_BIN} -config ${LJ_CONFIG} ${LJ_OPTS} >>${LJ_LOG} 2>&1 &"
+ 
+### End Configuration Options ###
+ 
 . /etc/init.d/functions
-
-[ -e /etc/sysconfig/logstash-forwarder ] && . /etc/sysconfig/logstash-forwarder
-DAEMON_ARGS="${DAEMON_ARGS:--config /etc/logstash-forwarder.conf -spool-size 100 -log-to-syslog}"
-
-start()
-{
+ 
+check_prereqs() {
+  if [ -z ${LJ_BIN} ]; then
+    echo "ERROR: Unable to locate Lumberjack binary, make sure it's installed."
+    exit 1
+  elif [ ! -f ${LJ_CONFIG} ]; then
+    echo "ERROR: LJ_CONFIG (${LJ_CONFIG}) doesn't exist."
+    exit 1
+  elif [ ! -d `dirname ${LJ_LOG}` ]; then
+    echo "ERROR: LJ_LOG parent directory (`dirname ${LJ_LOG}`) doesn't exist."
+    exit 1
+  elif [ ! -d ${LJ_RUNDIR} ]; then
+    echo "ERROR: LJ_RUNDIR (${LJ_RUNDIR}) doesn't exist."
+    exit 1
+  fi
+}
+ 
+start() {
+  check_prereqs
+ 
   echo -n $"Starting $NAME: "
-  nohup $DAEMON $DAEMON_ARGS >/dev/null 2>&1 &
-  RETVAL=$?
-  PID=$!
-  echo $PID > $PIDFILE
-  echo
-  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$NAME
-}
 
-stop()
-{
+  cd $LJ_RUNDIR && daemon --check $NAME --pidfile $PID_FILE $DAEMON
+ 
+  RETVAL=$?
+ 
+  if [ $RETVAL -ne 0 ]; then
+    echo_failure
+    echo
+  else
+    PID=$(pgrep ${NAME:0:15})
+    echo -n $PID > $PID_FILE
+    echo_success
+    echo
+  fi
+  return $RETVAL
+}
+ 
+stop () {
   echo -n $"Stopping $NAME: "
-  killproc -p "$PIDFILE" $DAEMON
+  killproc -p $PID_FILE $NAME
   RETVAL=$?
-  [ -f "$PIDFILE" ] && rm -f "$PIDFILE"
   echo
-  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$NAME
+  return $RETVAL
 }
-
+ 
 restart () {
   stop
   start
 }
-
-RETVAL=0
-
+ 
 case "$1" in
   start)
-    status -p $PIDFILE $NAME >/dev/null
-    RET=$?
-    if [ $RET -ne 0 ];then
-      start
-    fi
+    start
     ;;
   stop)
     stop
     ;;
-  restart|reload|force-reload)
+  status)
+    status -p $PID_FILE $NAME
+    ;;
+  restart)
     restart
     ;;
-  condrestart)
-    [ -f /var/lock/subsys/$NAME ] && restart || :
-    ;;
-  status)
-    status -p $PIDFILE $NAME
-    RETVAL=$?
-    ;;
   *)
-    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
-    RETVAL=1
+    echo "Usage: $0 {start|stop|status}"
+    exit 2
+    ;;
 esac
-
-exit $RETVAL
+ 
+exit $?
